### ISSUE TITLE
[Question] which k8s versions  are supported by superedge

### ISSUE THREAD

**Issue by yudar1024** [superedge/superedge#101]
I wanna know supported k8s versions of supperedge. can you kindly give a list. i didn't find it in doc.

**Comment by neweyes** [comment]
1.16/1.18 are fully tested，It is known that there is a compatibility problem with version 1.20. [issue](https://github.com/superedge/superedge/issues/72)

The version compatibility list with Kubernetes is very important. We will provide it as soon as possible. Thank you for your helpful suggestions
