### ISSUE TITLE
Go lint fix error and support Go 1.15

### ISSUE THREAD

**Issue by swartz-k** [superedge/superedge#13]
Hey，while i run `make lint`，i have meet some error，like below，is there need to solve them？or only I had meet those？
![image](https://user-images.githubusercontent.com/49771587/103173818-7a5bd680-4898-11eb-8df4-d8e912cd1a78.png)

**Comment by neweyes** [comment]
Yes, it needs to be fixed. The generated code is not recommended to be repaired, and the code of the project itself needs to be repaired. Do you have time to fix it?

![image](https://user-images.githubusercontent.com/8642098/103210091-a0888180-493f-11eb-9f15-f2b679b24895.png)

**Comment by swartz-k** [comment]
> Yes, it needs to be fixed. The generated code is not recommended to be repaired, and the code of the project itself needs to be repaired. Do you have time to fix it?
> 
> ![image](https://user-images.githubusercontent.com/8642098/103210091-a0888180-493f-11eb-9f15-f2b679b24895.png)

Thanks，My pleasure.

**Comment by neweyes** [comment]
go 1.16 supported
