### ISSUE TITLE
Support custom cofiguration where running install script

### ISSUE THREAD

**Issue by redwolf2019** [superedge/superedge#130]
**What would you like to be added/modified**:
- When user use the `auto install` script(look like `./edgeadm init --kubernetes-version=1.18.2 --image-repository superedge.tencentcloudcr.com/superedge --service-cidr=10.96.0.0/12 --pod-network-cidr=192.168.0.0/16 --install-pkg-path ./kube-linux-*.tar.gz --apiserver-cert-extra-sans=<Master public IP> --apiserver-advertise-address=<master Intranet IP> --enable-edge=true -v=6
`),we want to allow user to config there own configuration,such as `doker root path:  /var/lib/docker instead of /data/docker`.

**Why is this needed**:
- Use the default arguments, such as ` /var/lib/docker` ,not production ready, only be used to test.

**Comment by neweyes** [comment]
This is a very useful enhancement to meet the needs of many users in the production environment
