### ISSUE TITLE
When using edgeadm-v0.3.0 to deploy an edge cluster, docker cannot get up; and restarting the edge node will cause the node to fail to start normally

### ISSUE THREAD

**Issue by k2let** [superedge/superedge#131]
**What happened**:
When using edgeadm-v0.3.0 to deploy an edge cluster, docker cannot get up; and restarting the edge node will cause the node to fail to start normally

**What you expected to happen**:
Docker can start normally, and restart the edge node, the node can join the cluster normally

**How to reproduce it (as minimally and precisely as possible)**:
1. version of centOS: CentOS Linux release 7.8.2003 (Core)
2. firewalld is activated by default
3. selinux is started by default

**Environment**:
- SuperEdge version: 
    {
       "gitVersion": "v0.3.0",
       "gitBranch": "main",
       "gitCommit": "9982477207523ce376144e64fe5c59b648b944c9",
       "gitTreeState": "clean",
       "buildDate": "2021-05-20T04:01:30Z",
       "goVersion": "go1.14.14",
       "compiler": "gc",
       "platform": "linux/amd64"
    }

- Kubernetes version (use `kubectl version`):    
      Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"31a3f7703ac622535d4d453fe366f9746b450463", GitTreeState:"clean", BuildDate:"2020-10-13T12:50:07Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
      Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. `cat /etc/os-release`):  
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="7"
    PRETTY_NAME="CentOS Linux 7 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:7"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    
    CENTOS_MANTISBT_PROJECT="CentOS-7"
    CENTOS_MANTISBT_PROJECT_VERSION="7"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): Linux k8s-edge01 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Hardware configuration (e.g. `lscpu`) :  
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 142
Model name:            Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Stepping:              10
CPU MHz:               1991.999
BogoMIPS:              3983.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d

- Go Version (e.g. `go version`):  go version go1.16.4 linux/amd64
- Others:

**Comment by neweyes** [comment]
Thank you for your contribution, which is a very useful pr that can help many users who open SELinux by default
