### ISSUE TITLE
[Question] cni config uninitialized

### ISSUE THREAD

**Issue by meua** [superedge/superedge#171]
```
Lease:
  HolderIdentity:  ubuntu-xenial
  AcquireTime:     <unset>
  RenewTime:       Fri, 25 Jun 2021 00:55:32 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletNotReady              runtime network not ready: NetworkReady=false **reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized**
Addresses:
  InternalIP:  10.0.2.15
  Hostname:    ubuntu-xenial

```

**Comment by meua** [comment]
> ```
> Lease:
>   HolderIdentity:  ubuntu-xenial
>   AcquireTime:     <unset>
>   RenewTime:       Fri, 25 Jun 2021 00:55:32 +0000
> Conditions:
>   Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
>   ----             ------  -----------------                 ------------------                ------                       -------
>   MemoryPressure   False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
>   DiskPressure     False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
>   PIDPressure      False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
>   Ready            False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletNotReady              runtime network not ready: NetworkReady=false **reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized**
> Addresses:
>   InternalIP:  10.0.2.15
>   Hostname:    ubuntu-xenial
> ```

install by the follow command.
`./edgeadm init --kubernetes-version=1.18.2 --image-repository superedge.tencentcloudcr.com/superedge --service-cidr=10.96.0.0/12 --pod-network-cidr=192.168.0.0/16 --install-pkg-path ./kube-linux-*.tar.gz --apiserver-cert-extra-sans=192.168.33.11 --apiserver-advertise-address=192.168.33.10 --enable-edge=false -v=6`

**Comment by meua** [comment]
> > ```
> > Lease:
> >   HolderIdentity:  ubuntu-xenial
> >   AcquireTime:     <unset>
> >   RenewTime:       Fri, 25 Jun 2021 00:55:32 +0000
> > Conditions:
> >   Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
> >   ----             ------  -----------------                 ------------------                ------                       -------
> >   MemoryPressure   False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
> >   DiskPressure     False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
> >   PIDPressure      False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
> >   Ready            False   Fri, 25 Jun 2021 00:52:33 +0000   Thu, 24 Jun 2021 23:57:01 +0000   KubeletNotReady              runtime network not ready: NetworkReady=false **reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized**
> > Addresses:
> >   InternalIP:  10.0.2.15
> >   Hostname:    ubuntu-xenial
> > ```
> 
> install by the follow command.
> `./edgeadm init --kubernetes-version=1.18.2 --image-repository superedge.tencentcloudcr.com/superedge --service-cidr=10.96.0.0/12 --pod-network-cidr=192.168.0.0/16 --install-pkg-path ./kube-linux-*.tar.gz --apiserver-cert-extra-sans=192.168.33.11 --apiserver-advertise-address=192.168.33.10 --enable-edge=false -v=6`

* Applying /etc/sysctl.conf ...
ip_vs_sh               16384  0
ip_vs_wrr              16384  0
ip_vs_rr               16384  0
ip_vs                 147456  6 ip_vs_rr,ip_vs_sh,ip_vs_wrr
nf_conntrack_ipv4      20480  9
nf_defrag_ipv4         16384  1 nf_conntrack_ipv4
nf_conntrack          106496  7 ip_vs,nf_nat,nf_nat_ipv4,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_netlink,nf_conntrack_ipv4
libcrc32c              16384  2 raid456,ip_vs

启动日志报如下错误：
```
 stderr: cni0: ERROR while getting interface flags: No such device
flannel.1: ERROR while getting interface flags: No such device
Cannot find device "cni0"
Cannot find device "flannel.1"
sed: can't read /etc/sysconfig/selinux: No such file or directory
sed: can't read /etc/selinux/config: No such file or directory
sysctl: /etc/sysctl.d/99-sysctl.conf(61): invalid syntax, continuing...
sysctl: /etc/sysctl.d/99-sysctl.conf(62): invalid syntax, continuing...
sysctl: /etc/sysctl.conf(61): invalid syntax, continuing...
sysctl: /etc/sysctl.conf(62): invalid syntax, continuing...

I0625 01:06:39.154620    4207 init_node.go:52] Init node success
```

**Comment by dodiadodia** [comment]
We have customized flannel to adapt SuperEdge. You can try the latest version 0.7.0 edgeadm. Thanks
