### ISSUE TITLE
希望优化tunnel-cloud/edge，增强云边协同互访

### ISSUE THREAD

**Issue by garywhat** [superedge/superedge#172]
**加强tunnel-cloud/edge适用范围**:

**让云到边，边到云，不仅仅是集群master和node/pod之间，其他应用也可以通过你们出色的tunnel进行轻松互访**:

**Comment by neweyes** [comment]
@00pf00

**Comment by neweyes** [comment]
Tunnel can be used to proxy business application traffic, [tunnel](https://github.com/superedge/superedge/blob/main/docs/components/tunnel.md)

**Comment by neweyes** [comment]
Superedge is planning to make tunnel applicable to more scenarios. You are welcome to discuss with us

**Comment by mqyang56** [comment]
I think https://github.com/kubeedge/edgemesh (iptables+libp2p) is an optional solution.
