### ISSUE TITLE
目前lite apiserver端口是固定的 建议改成可以指定端口

### ISSUE THREAD

**Issue by garywhat** [superedge/superedge#181]
**What would you like to be added/modified**:
因建议将lite apiserver端口改成可以指定
**Why is this needed**:
因为在实际生产环境部署过程中，端口不能保证6443可用

**Comment by neweyes** [comment]
@00pf00

**Comment by dodiadodia** [comment]
Lite-apiserver has supported the  virtual address, and tkeedgedns could be created when installing edgeadm. You can have a try
