### ISSUE TITLE
'docs/installation/install_manually.md' have two things to be fixed.

### ISSUE THREAD

**Issue by mqyang56** [superedge/superedge#207]
**What would you like to be added/modified**:
*docs/installation/install_manually.md* have two things to be fixed.
1. `cat << EOF >lite_apiserver.conf` replaces with `cat << EOF >lite-apiserver.conf`
2. `Copy lite-apiserver.crt and lite-apiserver.key into edge worker node, path at /etc/kubernetes/pki/` replaces with `Copy lite-apiserver.crt and lite-apiserver.key into edge worker node, path at /etc/kubernetes/edge/`

**Why is this needed**:
   Manual-installation SuperEdge in the guide is imperfect.

**Comment by neweyes** [comment]
Thank you very much for pointing out the errors in the document. Can you submit PR to fix the errors？
