### ISSUE TITLE
hope to join both edge and no-edge nodes

### ISSUE THREAD

**Issue by haotaogeng** [superedge/superedge#223]
**What would you like to be added/modified**:
`
edgeadm init集群和join节点完全保留了kubeadm init/join原有的参数和流程，只是自动了初始化节点和安装容器运行时，可以用edgeadm --enable-edge=fasle参数来一键化安装原生Kubernetes集群， 也可以用edgeadm --enable-edge=true参数一键化来安装边缘Kubernetes集群。`

但目前只能加入同一类节点， 不能同时加入两类节点。

**Why is this needed**:
我们在搭建superedge的演示环境，需要尽可能贴近真实的环境，就是中心云里有多个普通节点，同时有多个边缘节点。这样就可以测试各种场景，包括云边通讯，边边通讯等。

**Comment by attlee-wang** [comment]
A good proposal 👍🏻👍🏻

**Comment by dodiadodia** [comment]
We are refactoring the edgeadm construct to use original kubeadm and superedge addon more clearly.
