### ISSUE TITLE
superedge部署--编译环境

### ISSUE THREAD

**Issue by hongfei-cloud** [superedge/superedge#23]
环境是kubernetes V1.16.15   docker-ce:18.09.9  golang:1.15.5 
请教一下：执行下面命令报错
[root@master ~]# kubectl apply -f tunnel-coredns.yaml
error: error parsing tunnel-coredns.yaml: error converting YAML to JSON: yaml: line 90: mapping values are not allowed in this context
是不是需要编译环境，编译的二进制文件tar.gz在哪里获取
谢谢！

**Comment by ruster-cn** [comment]
tunnel-coredns.yaml 文件第90行 应该写错了

**Comment by hongfei-cloud** [comment]
从github下载了，未经任何改动

**Comment by hongfei-cloud** [comment]
是从github下载的，未经任何改动

**Comment by attlee-wang** [comment]
@hongfei-cloud，@ruster-cn  我来验证下，如有问题，我来提个PR修复。

**Comment by hongfei-cloud** [comment]
另外请教下需要make build的源文件从哪里下载

**Comment by hongfei-cloud** [comment]
已经OK了！

**Comment by attlee-wang** [comment]
@hongfei-cloud 我下载源码运行并没有问题，您是怎么产生错误的？
![image](https://user-images.githubusercontent.com/57479557/105813287-9dd68600-5fea-11eb-84cf-617b3aca4760.png)

**Comment by hongfei-cloud** [comment]
谢谢您的回复！已经OK了，需要把页面上的yaml文件的代码复制到visual里再生成yaml文件。----- 原始邮件 -----
发件人：王冬 <notifications@github.com>
收件人：superedge/superedge <superedge@noreply.github.com>
抄送人：hongfei-cloud <hongfei_happy@sina.com>,  Mention <mention@noreply.github.com>
主题：Re:_[superedge/superedge]_superedge部署--编译环境_(#23)
日期：2021年01月26日 15点26分



@hongfei-cloud 我下载源码运行并没有问题，您是怎么产生错误的？

**Comment by neweyes** [comment]
This issue seems to be closed
