### ISSUE TITLE
[Question] Are all messages transmitted through the tunnel?

### ISSUE THREAD

**Issue by tiezhuoyu** [superedge/superedge#230]
Are all messages transmitted through the tunnel?  Or just part of them such as logs and exec message? Thank you.

**Comment by neweyes** [comment]
Tunnel forwards the traffic of apiserver and promethues by default, such as kubectl exec / logs. There are two ways to make tunnel agent other traffic:
1. You can modify the configuration of the tunnel to proxy other traffic,
2. You can deploy another set of tunnel cloud and tunnel edge to proxy the traffic you want
At present, tunnel supports proxy HTTP (s) / TCP / SSH protocol

tunnel usage: [English](https://github.com/superedge/superedge/blob/main/docs/components/tunnel.md)/[中文](https://github.com/superedge/superedge/blob/main/docs/components/tunnel_CN.md)

**Comment by tiezhuoyu** [comment]
Thanks for your reply!
