### ISSUE TITLE
stat ~/.kube/config: no such file or directory

### ISSUE THREAD

**Issue by bryant-rh** [superedge/superedge#231]
./edgeadm addon edge-apps --ca.cert /etc/kubernetes/pki/ca.crt --ca.key /etc/kubernetes/pki/ca.key --master-public-addr https://
**What happened**:
![image](https://user-images.githubusercontent.com/43403977/131483079-9cf3bc17-cdad-4faa-a92c-8cc4aa93d1ee.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- SuperEdge version: v0.5.0
- Kubernetes version (use `kubectl version`): 
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Hardware configuration (e.g. `lscpu`)
- Go Version (e.g. `go version`)
- Others:

**Comment by attlee-wang** [comment]
You need to show the path specified --kubeconfig
