### ISSUE TITLE
Cloud tunnel hangs up when exec into edge pods

### ISSUE THREAD

**Issue by duyanghao** [superedge/superedge#275]
**What happened**:
When I kubectl exec into mysql pods on edge, and execute sql query, the cloud-tunnel hangs up and no more output when sql result has large amounts data.

**What you expected to happen**:
Kubectl outputs sql results normally when it is large.

**Environment**:
- SuperEdge version: v0.3.0
- Kubernetes version (use `kubectl version`): v1.18.2
- OS (e.g. `cat /etc/os-release`): centos 7.8

**Comment by attlee-wang** [comment]
this problem has been solved. @duyanghao
