### ISSUE TITLE
edgeadm Not support Kubernetes v1.22

### ISSUE THREAD

**Issue by willgo-cn** [superedge/superedge#277]
Hello:
    edgeadam Not support Kubernetes v1.22,
    casue in Kubernetes v1.22 has remove admissionregistration.k8s.io/v1beta1 API versions
    so i use edgeadm in my cluster, i get error unable to create MutatingWebhookConfiguration: the server could not find the requested    resource

**Comment by lianghao208** [comment]
Thanks for the issue, we are planning to support v1.22. And you are more than welcome to submit PR if you are interested.

**Comment by dodiadodia** [comment]
The superedge and edgeadm are all compatible with kubernetes1.22. You can refer to edgeadm's main branch to have a try. Thanks.
