### ISSUE TITLE
边缘节点跟云端断连后再重新连上会导致节点上的pod重启

### ISSUE THREAD

**Issue by sixther-dc** [superedge/superedge#28]
条件： 在边缘节点可以连通云端组件的apiserver的时候，节点处于ready状态，pod也运行正常。 网络异常导致断联后节点处于notready状态（正常现象），pod的状态显示如下：
![image](https://user-images.githubusercontent.com/10322318/105140577-e0074f80-5b32-11eb-9b88-d2ef09980ebe.png)

网络恢复正常会，pod状态，节点状态恢复为正常，但是节点上的pod被重启了
![image](https://user-images.githubusercontent.com/10322318/105140645-fad9c400-5b32-11eb-9bea-a92686d12f27.png)

这里是不是需要有一个什么机制检测边缘节点的pod状态，如果跟中心的状态一致就可以不用重启。

**Comment by chenkaiyue** [comment]
请问部署edge-health了？

**Comment by sixther-dc** [comment]
> 请问部署edge-health了？

这个还没有，我研究下，请问edge-health是解决这个场景么

**Comment by chenkaiyue** [comment]
> > 请问部署edge-health了？
> 
> 这个还没有，我研究下，请问edge-health是解决这个场景么

是的
