### ISSUE TITLE
[Question] ServiceGrdi annotations lost

### ISSUE THREAD

**Issue by WaylandWong** [superedge/superedge#309]
I'm using kong ingress with servicegroup and found something error because the servicegrid annotations was not applied to the service.
By adding an annotation 'ingress.kubernetes.io/service-upstream: "true"' in service would make kong ingress proxy HTTP request by service instead of pods' endpoint, thus the kong ingress would be used in super edge with servicegrid.
When I add the listed annotation the ingress works well. 
Is there any way to keep annotations in the service?

what servicegrid looks like:
```yaml
apiVersion: superedge.io/v1
kind: ServiceGrid
metadata:
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    k8s-app: demo
  name: demo
  namespace: default
spec:
  gridUniqKey: zone
  template:
    ports:
    - name: demo-port
      port: 80
      protocol: TCP
      targetPort: 9527
    selector:
      k8s-app: demo
    sessionAffinity: None
```

what service I get :
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    topologyKeys: '["zone"]'
  creationTimestamp: "2022-01-18T14:22:02Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s-app: demo
    superedge.io/grid-selector: demo
    superedge.io/grid-uniq-key: zone
  name: demo-svc
  namespace: default
  ownerReferences:
  - apiVersion: superedge.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: ServiceGrid
    name: demo
    uid: 47261272-0e9b-4434-b9a2-26c6fcc6054d
  resourceVersion: "732525"
  selfLink: /api/v1/namespaces/default/services/demo-svc
  uid: 599daf62-a174-45fc-bb3a-d1715b9e02c4
spec:
  clusterIP: 10.110.117.74
  ports:
  - name: demo-port
    port: 80
    protocol: TCP
    targetPort: 9527
  selector:
    k8s-app: demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

---
您好，我在使用servicegrid的时候在`metadata`中添加了`annotations`，但是在servicegrid创建出来的service中没有看到这个`annotations`，请问servicegrid有什么办法可以保持添加的`annotations`不变吗？
具体的yaml资源请看上面，使用这个`annotations`的主要原因是控制kong ingress 的逻辑。

**Comment by attlee-wang** [comment]
OK, thanks for your feedback on this issue. This may be a ServiceGrid logic problem, we will deal with it as soon as possible！
