### ISSUE TITLE
kubelet print Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring

### ISSUE THREAD

**Issue by wangqifox** [superedge/superedge#365]
**What happened**:

In edge node，kubelet print 'Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring' frequently。
<img width="1210" alt="截屏2022-03-23 10 20 11" src="https://user-images.githubusercontent.com/1841066/159611138-bdea78aa-1d70-4d6b-9537-f7b9a5894deb.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
just install superedge, show kubelet's log with this command in edge node: "journalctl -u kubelet.service -f"

**Anything else we need to know?**:

**Environment**:
- SuperEdge version: v0.7.0
- Kubernetes version (use `kubectl version`): v1.20.6
- OS (e.g. `cat /etc/os-release`): 18.04.4 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):  Linux edge1 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Hardware configuration (e.g. `lscpu`)  x86_64 Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
- Go Version (e.g. `go version`) 
- Others:

**Comment by dodiadodia** [comment]
edgeadm doesn't create the manifest directory. It has no effect on functionality.
