### ISSUE TITLE
[Question] Does SuperEdge support Isito?

### ISSUE THREAD

**Issue by FengGaoCSC** [superedge/superedge#384]
I want to use SuperEdge to make some demo with Istio, Dose SuperEdge support Istio service mesh  as Kubernets mainline?

**Comment by dodiadodia** [comment]
@FengGaoCSC Yes，you can deploy istiod at edge nodes( limited in the same location, such as nodeunit principle)，and this behavior is equal to deploy istio in standard Kubernetes cluster. Now we just doesn't support deploying istio across multiple locations.

**Comment by dodiadodia** [comment]
Yes, we are planning to support multi-region pod accessing. The basic opinion is the same as：

**Comment by FengGaoCSC** [comment]
> Yes, we are planning to support multi-region pod accessing. The basic opinion is the same as：

thanks
