### ISSUE TITLE
Kubelet attempt to register node to lite-apiserver failed

### ISSUE THREAD

**Issue by yzping** [superedge/superedge#386]
**What happened**:
worker node lost connection to master node (kube-apiserver), and worker node get rebooted.After reboot, kubelet cannot pull pods/containers up.

**What you expected to happen**:
lite-apiserver should response to kubelet from cache, when kubelet attempt to register node.

**How to reproduce it (as minimally and precisely as possible)**:
1. shutdown master node（kube-apiserver）
2. reboot worker node

**Anything else we need to know?**:

Logs:
 kubelet: I0520 02:03:02.481940    1086 kubelet_node_status.go:71] Attempting to register node worker01
 lite-apiserver: I0520 02:03:02.482660    1098 proxy.go:71] New request: method->POST, url->/api/v1/nodes
 kubelet: E0520 02:03:03.025945    1086 file_linux.go:60] Unable to read config path "/etc/kubernetes/manifests": path does not exist, ignoring
 lite-apiserver: I0520 02:03:03.386833    1098 proxy.go:134] Request url=https://kubernetes.default:6443/apis/storage.k8s.io/v1/csinodes/worker01, error=dial tcp x.x.x.x:6443: i/o timeout
 lite-apiserver: I0520 02:03:03.386916    1098 proxy.go:221] request resourceInfo=&{IsResourceRequest:true Path:/apis/storage.k8s.io/v1/csinodes/worker01 Verb:get APIPrefix:apis APIGroup:storage.k8s.io APIVersion:v1 Namespace: Resource:csino1 Parts:[csinodes worker01]}
 lite-apiserver: I0520 02:03:03.386950    1098 proxy.go:147] Request error, need read data from cache

**Environment**:
- SuperEdge version: v0.7.0
- Kubernetes version (use `kubectl version`): v1.20.6
- OS (e.g. `cat /etc/os-release`): CentOS Linux release 7.2.1511 (Core) 
- Kernel (e.g. `uname -a`): kernel-4.18.0-240.15.1
- Hardware configuration (e.g. `lscpu`) Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
- Go Version (e.g. `go version`) go1.15.10 linux/amd64
- Others:

**Comment by dodiadodia** [comment]
Yes, the v0.7.0 version actually contains this issu that has been fixed by #366 . You can build the lite-apiserver binary from the source code.

**Comment by dodiadodia** [comment]
There is also a critical problem: the`application-grid-wrapper` deals with iptables not correctly
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/4024470/171991273-a815d29d-42a9-41f7-b5e6-b5357f2cba46.png">
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/4024470/171991280-f0c550bf-c564-44ed-9703-397b31003f8e.png">
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/4024470/171991287-2bd8ff18-6d87-4bcd-a399-64d0c82ff7d3.png">
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/4024470/171991309-99c44ed3-ebc4-4da2-aec0-f4a2f2c0cf33.png">
In-cluster url access may redirect to cloud apiserver and lite-apiserver a half chance. @malc0lm
