### ISSUE TITLE
kubeadm create edge-kube-proxy comfigmap err

### ISSUE THREAD

**Issue by lyllove** [superedge/superedge#390]
version:0.7.0
func：updateKubeProxyKubeconfig 

edgeKubeProxyCM := kubeProxyCM.DeepCopy()
edgeKubeProxyCM.Name = constant.EdgeKubeProxy
edgeKubeProxyCM.Namespace = constant.NamespaceKubeSystem
.....
kubeClient.CoreV1().ConfigMaps(constant.NamespaceEdgeSystem).Create(context.TODO(), edgeKubeProxyCM, metav1.CreateOptions{})
...

创建configmap中edgeKubeProxyCM的namespace是kube-system，与constant.NamespaceEdgeSystem不对应
提示 "the namespace of the provided object does not match the namespace sent on the request"

**Comment by malc0lm** [comment]
https://github.com/superedge/superedge/pull/392 fixed this issue, closed.
