### ISSUE TITLE
What is the biggest difference between superedge and kubeedge？

### ISSUE THREAD

**Issue by chenpfeisoo** [superedge/superedge#4]
What is the biggest difference between superedge and kubeedge？
Can I provide a different list from the architecture and scenario

**Comment by neweyes** [comment]
The biggest difference is that superedge is not intrusive to kubernetes source code, so it is not necessary to consider the compatibility with kubernetes version and ecology in theory

**Comment by chenpfeisoo** [comment]
so coool ！

**Comment by smartding** [comment]
A better question would be: what's the biggest difference between superedge and openyurt

**Comment by duyanghao** [comment]
> A better question would be: what's the biggest difference between superedge and openyurt

Well, the biggest difference between superedge and openyurt is that SuperEdge supports serviceGroup and distributed health check besides Kubernetes-native and Edge autonomy.
Take a look at this [post](https://duyanghao.github.io/superedge/), which may help you dive into details.
