### ISSUE TITLE
在已有k8s集群上部署superedge 报错 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by baizipo** [superedge/superedge#406]
**What happened**: 在已有k8s环境上部署报错  panic: runtime error: invalid memory address or nil pointer dereference

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:  
- SuperEdge version: v0.7 
- Kubernetes version (use `kubectl version`): v1.20.7
- OS (e.g. `cat /etc/os-release`): centos7.9
- Kernel (e.g. `uname -a`):  5.18.5-1.el7.elrepo.x86_64
- Hardware configuration (e.g. `lscpu`) 2c/4G/160G
- Go Version (e.g. `go version`)
- Others:

**Comment by dodiadodia** [comment]
@baizipo 您方便描述一下具体复现的过程么？以及您这版使用的 0.7.0 版本的包地址？最近 superedge 的main 主线版本处理了一些之前 0.7.0 遗留的 bug，可以用最新的版本测试...具体情况咱们可已在这里沟通

**Comment by baizipo** [comment]
好的，我把步骤完善如下:
1. 使用kubespray v2.16.0 部署k8s v1.20.7(最接近superedge文档中的 v1.20.6版本)    1master +1node
2. 部署superedge，参考https://github.com/superedge/edgeadm/blob/main/docs/installation/addon_superedge_CN.md
3.  下载edgeadm安装包
```
arch=amd64 version=v0.7.0 kubernetesVersion=1.20.6 && rm -rf edgeadm-linux-* && wget https://superedge-1253687700.cos.ap-guangzhou.myqcloud.com/$version/$arch/edgeadm-linux-$arch-$version-k8s-$kubernetesVersion.tgz && tar -xzvf edgeadm-linux-* && cd edgeadm-linux-$arch-$version-k8s-$kubernetesVersion && ./edgeadm
```
4. addon Superedge 报错参考图片
![superedge](https://user-images.githubusercontent.com/21102087/174946411-4e9e1661-d2b7-4924-b1ce-8a5abe8af143.png)

**Comment by dodiadodia** [comment]
@baizipo 这个问题已经在 edgeadm 子项目中修复，请参考：https://github.com/superedge/edgeadm/pull/19
您可以从https://github.com/superedge/edgeadm 这项目中使用 release-1.20 分支，自行编译一个 edgeadm 替换现有二进制进行下测试，有问题请反馈

**Comment by dodiadodia** [comment]
@baizipo 因为 superedge 有一些依赖的配置和 image 镜像版本，建议用 edgeadm init 直接初始化一个集群的方式来使用，比 addon方式的问题更少一些

**Comment by baizipo** [comment]
收到，感谢
