### ISSUE TITLE
flannel in edge node CrashLoopBackOff

### ISSUE THREAD

**Issue by vertee** [superedge/superedge#409]
`kube-flannel I0627 09:46:46.691017       1 main.go:518] Determining IP address of default interface   `                                                                                 
`kube-flannel I0627 09:46:46.691288       1 main.go:531] Using interface with name eth0 and address 10.71.6.70 `                                                                           
`kube-flannel I0627 09:46:46.691305       1 main.go:548] Defaulting external address to interface address (10.71.6.70)    `                                                                
`kube-flannel W0627 09:46:46.691312       1 client_config.go:517] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work. `
`kube-flannel E0627 09:47:16.692645       1 main.go:243] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-x6vl8': Get "https://10.96.0.1:443/ap `
`Stream closed EOF for kube-system/kube-flannel-ds-x6vl8 (install-cni)   `                                                                                                                 
`Stream closed EOF for kube-system/kube-flannel-ds-x6vl8 (kube-flannel) `

**Comment by dodiadodia** [comment]
Can you describe the way you are using to deploy superedge cluster in detail? If you are using edgeadm init?

**Comment by vertee** [comment]
> Can you describe the way you are using to deploy superedge cluster in detail? If you are using edgeadm init?

yes. 
`./edgeadm init --kubernetes-version=1.20.6 --image-repository superedge.tencentcloudcr.com/superedge  --service-cidr=10.96.0.0/12 --pod-network-cidr=192.168.0.0/16 --install-pkg-path ./kube-linux-*.tar.gz --apiserver-cert-extra-sans=103.229.213.219 --apiserver-advertise-address=10.100.13.172 --enable-edge=true`

`edgeadm join 103.229.213.219:6443 --token fx1e82.evkr8axs8kmu9jti \
--discovery-token-ca-cert-hash sha256:acd844afce1181a1dd5e323948edf4b4373867fe5599bac8af7242e7c7764090  \
--install-pkg-path /data/superedge/kube-linux-*.tar.gz --enable-edge=true -v 6`

**Comment by dodiadodia** [comment]
I have no clue about this issue. We tested `edgeadm init` on our VM and don't reoccur this problem. I suggest you can use the internal ip 10.100.13.172  to see if it can successfully join the cluster? Or can you describe your environment more clearly, especially the internal and external network configuration, and OS version?
