### ISSUE TITLE
[Question] how to enable edge-health plugin

### ISSUE THREAD

**Issue by slm940208** [superedge/superedge#412]
https://github.com/superedge/superedge/blob/164e6f3bd1ea333f66a80c8f39ff782298a59b08/pkg/edge-health/checkplugin/kubeletcheck.go#L70

A parameter enabled by the plug-in is added in the code, but no side is set to true. How to set startup args?

**Comment by flower01840** [comment]
same question

**Comment by dodiadodia** [comment]
edge-health进行了重构，可以试用下v0.8.2新版
