### ISSUE TITLE
[Question]Setup prometheus and node-export stack

### ISSUE THREAD

**Issue by walk1ng** [superedge/superedge#413]
Hi Team,
We are working with superedge (amd64-v0.7.0-k8s-1.20.6), and try to setup Prometheus/node-exporter monitoring stack refer to the [document](https://github.com/superedge/superedge/blob/main/docs/components/deploy-monitor_CN.md).

The cluster is composed of 3 masters + 2 cloud node + 1 edge node.

The k8s sd endpoints are down with issues, see:
![ep](https://user-images.githubusercontent.com/6767972/176875580-313c7369-c754-466b-9085-e1afa54efaa9.png)

- cloud-node-001 > a cloud node
- 10.96.28.203:53 > tunnel-coredns svc cluster-ip
- edge-node-002 > a edge node (ip: 10.71.6.118)
- 192.168.0.2 > the tunnel-cloud pod which map with edge-node-002

as you see, the tunnel-coredns lookup nodes failed except for edge, but edge connection refused.

noticed that there are errors in tunnel-cloud pod as follow:
` 
E0701 10:26:59.813870       1 egress_server.go:39] Failed to get http request, error: read tcp 192.168.0.2:8000->192.168.0.1:5187: read: connection reset by peer
E0701 10:27:00.197754       1 proxy.go:52] Failed to send request from tunnel-cloud, error: dial tcp 10.71.6.118:10250: connect: connection timed out                                                                    
`
my configmaps tunnel-cloud-conf and tunnel-edge-conf are generated by default edgeadm init process.

does any configurations missing? cloud you help to figure out.
any help will be really appreciated.

**Comment by dodiadodia** [comment]
@malc0lm Please help to check this issue

**Comment by 00pf00** [comment]
This problem has been solved in release v0.8.0, you can replace the tunnel-cloud image with v0.8.0

**Comment by dodiadodia** [comment]
@walk1ng Yes, you can edit the tunnel-cloud deployment to version v0.8.0. We have tested this version. But there maybe another issue is that prometheus can't get the master node's target. You have to configure the Prometheus configuration to adapt the master node's monitoring.

**Comment by walk1ng** [comment]
thanks @dodiadodia @00pf00 for your feedback. 
the edge node metrics can be discovered, but how to resolve the master and cloud nodes?

**Comment by dodiadodia** [comment]
@walk1ng At present,  I suggest you to use 2 jobs to discorver master node and edge node. To discover the edge node you can use our Prometheus config, and then add another job to discorver master node.

**Comment by dodiadodia** [comment]
@walk1ng 新版本v0.8.2彻底解决了云上 node 和边缘 node 对监控的支持依赖，欢迎试用测试
