### ISSUE TITLE
[Question]边缘节点tunnel-edge反复重启，且无法正常查看pod日志及无法SSH连接

### ISSUE THREAD

**Issue by qa137** [superedge/superedge#414]
边缘节点tunnel-edge反复重启，同时也无法查看日志，ssh连接也无法使用，pod部署是可以正常进行。尝试很多次，不知道出现问题在哪里

**全部通过一键安装程序edgeadm部署，边缘节点信息**
System OS: ubuntu 20.04 （VMware 虚拟机系统）
kubernetes-version：1.20.6
Superedge -version: 0.7.0

<img width="1171" alt="截屏2022-07-04 上午12 25 20" src="https://user-images.githubusercontent.com/3113623/177048718-411b0b87-9e55-4095-bfc7-3c89c58a7169.png">

**以下为kubectl describe tunnel-edge出现异常的信息**
  Normal   Scheduled  44m                  default-scheduler  Successfully assigned edge-system/tunnel-edge-8tnbh to edge-dev
  Normal   Pulling    44m                  kubelet            Pulling image "superedge.tencentcloudcr.com/superedge/tunnel:v0.7.0"
  Normal   Pulled     44m                  kubelet            Successfully pulled image "superedge.tencentcloudcr.com/superedge/tunnel:v0.7.0" in 15.57385848s
  Normal   Killing    34m                  kubelet            Container tunnel-edge failed liveness probe, will be restarted
  Normal   Created    30m (x5 over 44m)    kubelet            Created container tunnel-edge
  Normal   Started    30m (x5 over 43m)    kubelet            Started container tunnel-edge
  Warning  Unhealthy  28m (x5 over 43m)    kubelet            Liveness probe failed: HTTP probe failed with statuscode: 500
  Warning  BackOff    9m6s (x59 over 37m)  kubelet            Back-off restarting failed container
  Normal   Pulled     4m5s (x9 over 40m)   kubelet            Container image "superedge.tencentcloudcr.com/superedge/tunnel:v0.7.0" already present on machine

**边缘节点docker tunnel-edge日志信息：**
I0703 16:25:59.464005       1 server.go:42] Versions: version.Info{GitVersion:"v0.7.0", GitBranch:"v0.7.0", GitCommit:"75b97d99f0f029a9f898f1f7992089093f602dc2", GitTreeState:"clean", BuildDate:"2022-06-17T07:16:49Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
I0703 16:25:59.464310       1 streaminterceptor.go:257] stream clinet token nodename = edge-dev token = BpLnfgDsc2WD8F2qNfHK5a84jjJkwzDk
I0703 16:25:59.464342       1 stream.go:85] init module: stream success !
I0703 16:25:59.464352       1 egress.go:81] init module: egress success !
I0703 16:25:59.464360       1 tcp.go:87] init module: tcp success !
I0703 16:25:59.464362       1 https.go:51] init module: https success !
I0703 16:25:59.464383       1 ssh.go:60] init module: ssh success !
I0703 16:25:59.464393       1 core.go:31] starting module:https
I0703 16:25:59.464397       1 core.go:33] start module:https success !
I0703 16:25:59.464400       1 core.go:31] starting module:ssh
I0703 16:25:59.464405       1 core.go:33] start module:ssh success !
I0703 16:25:59.464410       1 core.go:31] starting module:stream
I0703 16:25:59.464434       1 core.go:33] start module:stream success !
I0703 16:25:59.464436       1 core.go:31] starting module:egress
I0703 16:25:59.464439       1 core.go:33] start module:egress success !
I0703 16:25:59.464441       1 core.go:31] starting module:tcp
I0703 16:25:59.464466       1 core.go:33] start module:tcp success !
I0703 16:25:59.558325       1 grpcserver.go:108] channelz server listening address is not configured
I0703 16:25:59.657672       1 grpcserver.go:99] log server listen on 0.0.0.0:51010

**Comment by 00pf00** [comment]
The connection between tunnel-edge and tunnel-cloud was not established successfully

**Comment by dodiadodia** [comment]
@qa137 您可以更新一下 tunnel-cloud 和 tunnel-edge 到 v0.8.0版本，看看是否还有问题，有问题的话这里反馈，谢谢

**Comment by qa137** [comment]
@dodiadodia 非常感谢！！！
但v0.8.0版本镜像不可用：HTTP request sent, awaiting response... 404 Not Found

**Comment by qa137** [comment]
目前经过多次尝试，在master节点加入边缘节点edge后，会造成边缘kube-flannel错误重启2次，边缘edge-health也会重启1次

<img width="1156" alt="截屏2022-07-04 下午11 40 00" src="https://user-images.githubusercontent.com/3113623/177186042-c1386b66-aaff-4ede-8d7b-1e05705540af.png">

**Comment by qa137** [comment]
@dodiadodia 非常感谢

**Comment by dodiadodia** [comment]
@qa137 我这里用腾讯云的带公网 IP 的节点 + 本地 virtualbox 生成的虚拟机（NAT 访问公网）的方式测试了一下，没有发现您这边描述的问题哈，如下图：

**Comment by qa137** [comment]
@dodiadodia 之前换了阿里云其他区域服务器过后，管了几天时间没问题。然后过几天又出现相同的重启问题，现在都不知道是网络问题，还是其他问题了。能否通过阿里云服务器做一下相关测试，谢谢！

**部通过一键安装程序edgeadm部署，边缘节点信息**
System OS: ubuntu 20.04 （VMware 虚拟机系统）
kubernetes-version：1.22.6
Superedge -version: 0.8.0

**异常信息**
  Normal   Killing    38m                  kubelet  Container tunnel-edge failed liveness probe, will be restarted
  Normal   Created    33m (x5 over 127m)   kubelet  Created container tunnel-edge
  Normal   Pulled     33m (x4 over 43m)    kubelet  Container image "superedge.tencentcloudcr.com/superedge/tunnel:v0.8.0" already present on machine
  Normal   Started    33m (x5 over 127m)   kubelet  Started container tunnel-edge
  Warning  Unhealthy  8m11s (x8 over 44m)  kubelet  Liveness probe failed: HTTP probe failed with statuscode: 500
  Warning  BackOff    4m4s (x84 over 40m)  kubelet  Back-off restarting failed container

**Comment by dodiadodia** [comment]
@qa137 这里我们找个环境也做个长期测试

**Comment by 00pf00** [comment]
> 边缘节点tunnel-edge反复重启，同时也无法查看日志，ssh连接也无法使用，pod部署是可以正常进行。尝试很多次，不知道出现问题在哪里
> 
> **全部通过一键安装程序edgeadm部署，边缘节点信息** System OS: ubuntu 20.04 （VMware 虚拟机系统） kubernetes-version：1.20.6 Superedge -version: 0.7.0
> 
> <img alt="截屏2022-07-04 上午12 25 20" width="1171" src="https://user-images.githubusercontent.com/3113623/177048718-411b0b87-9e55-4095-bfc7-3c89c58a7169.png">
> 
> **以下为kubectl describe tunnel-edge出现异常的信息** Normal Scheduled 44m default-scheduler Successfully assigned edge-system/tunnel-edge-8tnbh to edge-dev Normal Pulling 44m kubelet Pulling image "superedge.tencentcloudcr.com/superedge/tunnel:v0.7.0" Normal Pulled 44m kubelet Successfully pulled image "superedge.tencentcloudcr.com/superedge/tunnel:v0.7.0" in 15.57385848s Normal Killing 34m kubelet Container tunnel-edge failed liveness probe, will be restarted Normal Created 30m (x5 over 44m) kubelet Created container tunnel-edge Normal Started 30m (x5 over 43m) kubelet Started container tunnel-edge Warning Unhealthy 28m (x5 over 43m) kubelet Liveness probe failed: HTTP probe failed with statuscode: 500 Warning BackOff 9m6s (x59 over 37m) kubelet Back-off restarting failed container Normal Pulled 4m5s (x9 over 40m) kubelet Container image "superedge.tencentcloudcr.com/superedge/tunnel:v0.7.0" already present on machine
> 
> **边缘节点docker tunnel-edge日志信息：** I0703 16:25:59.464005 1 server.go:42] Versions: version.Info{GitVersion:"v0.7.0", GitBranch:"v0.7.0", GitCommit:"75b97d99f0f029a9f898f1f7992089093f602dc2", GitTreeState:"clean", BuildDate:"2022-06-17T07:16:49Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"} I0703 16:25:59.464310 1 streaminterceptor.go:257] stream clinet token nodename = edge-dev token = BpLnfgDsc2WD8F2qNfHK5a84jjJkwzDk I0703 16:25:59.464342 1 stream.go:85] init module: stream success ! I0703 16:25:59.464352 1 egress.go:81] init module: egress success ! I0703 16:25:59.464360 1 tcp.go:87] init module: tcp success ! I0703 16:25:59.464362 1 https.go:51] init module: https success ! I0703 16:25:59.464383 1 ssh.go:60] init module: ssh success ! I0703 16:25:59.464393 1 core.go:31] starting module:https I0703 16:25:59.464397 1 core.go:33] start module:https success ! I0703 16:25:59.464400 1 core.go:31] starting module:ssh I0703 16:25:59.464405 1 core.go:33] start module:ssh success ! I0703 16:25:59.464410 1 core.go:31] starting module:stream I0703 16:25:59.464434 1 core.go:33] start module:stream success ! I0703 16:25:59.464436 1 core.go:31] starting module:egress I0703 16:25:59.464439 1 core.go:33] start module:egress success ! I0703 16:25:59.464441 1 core.go:31] starting module:tcp I0703 16:25:59.464466 1 core.go:33] start module:tcp success ! I0703 16:25:59.558325 1 grpcserver.go:108] channelz server listening address is not configured I0703 16:25:59.657672 1 grpcserver.go:99] log server listen on 0.0.0.0:51010

从这个日志可显示是边缘节点没有注册成功
注册成功会输出日志，类似：
I0713 10:55:56.927320       1 streamclient.go:31] streamClient created successfully
I0713 10:55:56.927590       1 streaminterceptor.go:79] node added successfully node = vm-0-37-centos

**Comment by qa137** [comment]
@00pf00 感谢回复，我发现照成pod销毁的原因是grpc连接超时

我去看了一下grpcclient.go的源代码（go语言不会凭经验），根据grpc连接提供的ServerName连接地址和端口（tunnel-cloud的公网服务端口）都能够正常访问到，进容器中测试也是能够正常访问。
个人猜测是不是相关的证书未下发到边缘edge，或者是DNS有问题。或者是edgeadm安装程序在阿里云提供的ubuntu镜像不兼容的问题（阿里云默认账户为root）

<img width="1397" alt="截屏2022-07-14 上午12 55 09" src="https://user-images.githubusercontent.com/3113623/178790612-be371c64-1b3d-480d-ab9c-018bb8b1c8be.png">

**边缘master节点配置**
ubuntu 20.04.4（阿里云提供ubuntu镜像）
kubernetes-version：1.22.6
Superedge -version: 0.8.0

**边缘edge节点配置**
System OS: ubuntu 20.04.4 （VM虚拟机系统）
kubernetes-version：1.22.6
Superedge -version: 0.8.0

**下面是日志输出**
I0713 15:17:20.037280       1 server.go:45] Versions: version.Info{GitVersion:"v0.8.0", GitBranch:"main", GitCommit:"e2b9adaacc82be3c1863abc8b49347a93eabc32a", GitTreeState:"clean", BuildDate:"2022-06-13T03:00:34Z", GoVersion:"go1.17", Compiler:"gc", Platform:"linux/amd64"}
I0713 15:17:20.336398       1 streaminterceptor.go:257] stream clinet token nodename = edge-dev token = BpLnfgDsc2WD8F2qNfHK5a84jjJkwzDk
I0713 15:17:20.336439       1 stream.go:85] init module: stream success !
I0713 15:17:20.336444       1 egress.go:75] init module: egress success !
I0713 15:17:20.336446       1 tcp.go:87] init module: tcp success !
I0713 15:17:20.336449       1 https.go:51] init module: https success !
I0713 15:17:20.336451       1 ssh.go:62] init module: ssh success !
I0713 15:17:20.336454       1 http_proxy.go:82] init module: httpProxy success !
I0713 15:17:20.336467       1 core.go:31] starting module:stream
I0713 15:17:20.336495       1 core.go:33] start module:stream success !
I0713 15:17:20.336500       1 core.go:31] starting module:egress
I0713 15:17:20.336503       1 core.go:33] start module:egress success !
I0713 15:17:20.336505       1 core.go:31] starting module:tcp
I0713 15:17:20.336516       1 core.go:33] start module:tcp success !
I0713 15:17:20.336519       1 core.go:31] starting module:https
I0713 15:17:20.336523       1 core.go:33] start module:https success !
I0713 15:17:20.336525       1 core.go:31] starting module:ssh
I0713 15:17:20.336530       1 core.go:33] start module:ssh success !
I0713 15:17:20.336532       1 core.go:31] starting module:httpProxy
I0713 15:17:20.336535       1 core.go:33] start module:httpProxy success !
I0713 15:17:20.342113       1 grpcserver.go:99] log server listen on 0.0.0.0:51010
I0713 15:17:20.342982       1 grpcserver.go:108] channelz server listening address is not configured
E0713 15:20:20.685961       1 grpcclient.go:84] grpc connection rebuild timed out, container exited !

**Comment by dodiadodia** [comment]
@qa137 当出现这个问题的时候，您这边把相应的 CrashLoopBackOff的 pod 删掉重建一下，是否可以正常恢复呢？

**Comment by qa137** [comment]
不能，我反复测试多次。只要我知道的，都试过了，不好使

**Comment by dodiadodia** [comment]
@qa137 如果是这样的话，我仍然怀疑还是网络问题导致的； pod 重建后都无法正常连接，这个时候等于是初始化的状态了，不会有太多遗留问题影响。
我这里的环境running 了 41 个小时还没有复现您说的问题哈。建议您这边可以再 check 一下网络...

**Comment by qa137** [comment]
@dodiadodia 我提供了一台测试服务器，发您邮箱，请帮忙指导一下，非常感谢！

**Comment by dodiadodia** [comment]
> 

OK，我们试一下

**Comment by dodiadodia** [comment]
@qa137 我们基本上找到问题了，是 tunnel 使用的 tls 的证书的 server name 被阿里云 RST 了，修改下这里的配置，重启下 pod 就可以了：
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/4024470/179360375-e4dc5671-6063-4a7c-a756-8ead715fad6c.png">

**Comment by qa137** [comment]
我观察了12小时，已正常运行，非常感谢！

**Comment by dodiadodia** [comment]
@qa137 多谢在各种环境里尝试发现 superedge 的适配性问题，后面有任何问题和建议都可以在这里交流

**Comment by qa137** [comment]
@dodiadodia 今天在新的服务器上面程序部署了一次，又出现反复重启的问题。组要原因是edge-coredns连接超时照成相应kube-flannel和edge-health反复重启

**边缘master节点配置**
ubuntu 20.04.4（阿里云提供ubuntu镜像）
kubernetes-version：1.22.6
Superedge -version: 0.8.0

**边缘edge节点配置**
System OS: ubuntu 20.04.4 （VM虚拟机系统）
kubernetes-version：1.22.6
Superedge -version: 0.8.0

**错误日志信息**
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
I0726 08:28:13.930752       1 trace.go:116] Trace[336122540]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105 (started: 2022-07-26 08:27:43.929739635 +0000 UTC m=+62.910295058) (total time: 30.000954578s):
Trace[336122540]: [30.000954578s] [30.000954578s] END
E0726 08:28:13.930870       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Service: Get "https://10.244.0.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.244.0.1:443: i/o timeout
I0726 08:28:13.932471       1 trace.go:116] Trace[208240456]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105 (started: 2022-07-26 08:27:43.931524426 +0000 UTC m=+62.912079879) (total time: 30.00089309s):
Trace[208240456]: [30.00089309s] [30.00089309s] END
E0726 08:28:13.933875       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Namespace: Get "https://10.244.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.244.0.1:443: i/o timeout
I0726 08:28:14.016125       1 trace.go:116] Trace[646203300]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105 (started: 2022-07-26 08:27:43.932571809 +0000 UTC m=+62.913127235) (total time: 30.083057354s):
Trace[646203300]: [30.083057354s] [30.083057354s] END
E0726 08:28:14.016162       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Endpoints: Get "https://10.244.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.244.0.1:443: i/o timeout
[INFO] plugin/ready: Still waiting on: "kubernetes"

**Comment by qa137** [comment]
![1658824948662](https://user-images.githubusercontent.com/3113623/180968010-1e3b73f9-98ff-42b9-a0c2-e31d7ab008c3.jpg)
