### ISSUE TITLE
[Question]the edge-coredns has issue of resolve dns

### ISSUE THREAD

**Issue by walk1ng** [superedge/superedge#417]
hi team,
i am working on superedge  (amd64-v0.7.0-k8s-1.20.6) and hit the dns resolve issue on pods which are scheduled on edge nodes.
it can't resolve the service in pod(edge side), for example, failed to resolve a service `zhjc-admin-web-svc` in namespace `ns-ddj1faqs`:
`10.103.221.101` is the cluster ip of service `edge-system/ edge-coredns-svc`, the service link 3 edge-coredns pods for 2 edge nodes and master node:
```
bash-4.4# cat /etc/resolv.conf 
nameserver 10.103.221.101
search ns-ddj1faqs.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
bash-4.4# 
bash-4.4# nslookup zhjc-admin-web-svc
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'zhjc-admin-web-svc': Try again
bash-4.4# nslookup zhjc-admin-web-svc.ns-ddj1faqs
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'zhjc-admin-web-svc.ns-ddj1faqs': Try again
```
below is my edge-coredns configmap:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        hosts /etc/edge/hosts {
            reload 300ms
            fallthrough
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload 2s
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-08T06:07:58Z"
  name: edge-coredns
  namespace: edge-system
```
i try to bind the `10.103.221.101` in the edge-coredns configmap, but it cause the edge-coredns pods start failed with error:
```
[ERROR] Restart failed: Listen: listen tcp 10.103.221.101:53: bind: cannot assign requested address
[ERROR] plugin/reload: Corefile changed but reload failed: starting with listener file descriptors: Listen: listen tcp 10.103.221.101:53: bind: cannot assign requested address
```

cloud you please help to figure out how to troubleshooting this issue, any help will be really appreciated.

**Comment by dodiadodia** [comment]
I suggest you to try `nslookup zhjc-admin-web-svc.ns-ddj1faqs.svc`. And the coredns at egde node doesn't listen the "edge-system/ edge-coredns-svc" clusterip. You can login a pod on edge node and you'll see the following configuration:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/4024470/178148446-902670b1-e059-4f99-b416-61f1da72dda6.png">
The coredns listen on edge node's virutal IP and not your service clusterip '10.103.221.101'. The service ip will redirect the accessing flow to the master's pod ip, this is not accessible.

**Comment by liguobao** [comment]
+1

**Comment by dodiadodia** [comment]
新版本v0.8.2对 tunnel 进行了全面重构，解决了之前云边 node/pod/svc 通信的大部分问题，欢迎测试
