### ISSUE TITLE
[Question] statefulset-grid-daemon部署疑惑

### ISSUE THREAD

**Issue by flower01840** [superedge/superedge#424]
版本：用edgeadm-linux-amd64-v0.7.0-k8s-1.18.2.tgz部署的管理节点和edge节点

目的：实现statefulsetgrid + headless通过 {statefulsetgrid}-{0..N-1}.{servicegrid}-svc.namespace.svc.cluster.local访问同nodeunits下的headless

我部署statefulset-grid-daemon支持statefulset+headless的方式 ：
 1. 部署statefulset-grid-daemon，发现解析记录写在/data/edge/hosts文件
 2. 配置edge-coredns使用host plugins导入该文件

疑惑：因为根据serviceGroup_CN.md部署步骤，只有部署statefulset-grid-daemon的说明，并且说该服务会来更新节点侧的CoreDNS 信息，而实际按照文档部署后edge-coredns并没有相关DNS记录。所以疑惑是否是自己配置错误还是其他原因导致的

**Comment by dodiadodia** [comment]
@flower01840 经过测试，应该是这个链接里有个地址没有修改导致的，https://github.com/superedge/superedge/blob/main/deployment/statefulset-grid-daemon.yaml

**Comment by flower01840** [comment]
@dodiadodia 嗯对的，这是一处我自己调整过了，但是修改这处之后我的环境里edge-coredns也是没法解析headless的

我还修改了edge-coredns.yaml的一处，添加了一个hostpath：
spec:
  template:
    spec:
      containers:
        volumeMounts:
        - mountPath: /etc/edge/hosts
          name: hosts
      volumes:
      - hostPath:
          path: /data/edge/hosts
        name: hosts

主要是根据这个提示。
![image](https://user-images.githubusercontent.com/37743391/182280873-a5c445d7-a673-45bc-b0cc-57697e546663.png)

而statefulset-grid-daemon是将解析记录写在/data/edge/hosts文件的，所以做了上述修改

不知我的理解是否正确

**Comment by dodiadodia** [comment]
@flower01840 您的理解非常正确，这里dns 的配置没有在文档里提及，确实需要如此处理
