### ISSUE TITLE
停止服务器后，改变公网再次重启，kubectl port-forward出现异常

### ISSUE THREAD

**Issue by qa137** [superedge/superedge#431]
**What happened**:
关闭服务器且公网IP发生改变后，再次重启服务器，kubectl port-forward无法进行正确代理。出现以下异常信息
error: error upgrading connection: error dialing backend: proxy error from tunnel-cloud.edge-system.svc.cluster.local:8000 while dialing master:10250, code 500: 500 Internal Server Error
kubectl代理全部失效，目前只发现该问题。不知如何排查，请赐教！

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
使用如下命令或者相应svc都会异常
kubectl port-forward --address 0.0.0.0 svc/edge-health-admission -n edge-system 30333:443

**Environment**:
- SuperEdge version:
   SuperEdge V0.8
- Kubernetes version 
   Kubernetes V1.22.6
- OS (e.g. `cat /etc/os-release`):
   阿里云 Ubuntu 20.04

**Comment by dodiadodia** [comment]
@qa137 我们内部先测试复现下哈

**Comment by qa137** [comment]
今天重新安装了一个测试环境的superedge，安装好后kubectl port-forward能够正常运行。立马重启服务器后就无法使用了，报错
**error: error upgrading connection: error dialing backend: proxy error from tunnel-cloud.edgesystem.svc.cluster.local:8000 while dialing master:10250, code 500: 500 Internal Server Error**

之前以为是安装了其他程序照成无法使用，现在包括日志log都没法看，求助 @dodiadodia 

**运行环境:
SuperEdge V0.8
Kubernetes V1.22.6
阿里云ECS Ubuntu 20.04**

**Comment by liguobao** [comment]
+1，
看起来是同样的问题。
所有的容器实例都正常工作，但是无法查看日志。

**Comment by qa137** [comment]
重启服务器过后，会照成DNS错误，连接超时。相应的kubectl logs 和 kubectl port-forward 等命令都会失效
我分别在阿里云ubuntu服务器，腾讯云ubuntu服务器出现相同问题。 

ecs-user@master:~$ sudo crictl logs d71372066744e
I1019 08:30:43.689452       1 server.go:45] Versions: version.Info{GitVersion:"v0.8.0", GitBranch:"main", GitCommit:"4df29b218b82f43b6fdca5259a83faeb208240ff", GitTreeState:"dirty", BuildDate:"2022-07-25T08:59:06Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}
I1019 08:30:46.058139       1 stream.go:85] init module: stream success !
I1019 08:30:46.058752       1 egress.go:75] init module: egress success !
I1019 08:30:46.058832       1 tcp.go:87] init module: tcp success !
I1019 08:30:46.058898       1 https.go:51] init module: https success !
I1019 08:30:46.058931       1 ssh.go:62] init module: ssh success !
I1019 08:30:46.058961       1 http_proxy.go:82] init module: httpProxy success !
I1019 08:30:46.058997       1 core.go:31] starting module:stream
I1019 08:30:46.059017       1 core.go:33] start module:stream success !
I1019 08:30:46.059024       1 core.go:31] starting module:egress
I1019 08:30:46.060105       1 core.go:33] start module:egress success !
I1019 08:30:46.060129       1 core.go:31] starting module:tcp
I1019 08:30:46.060148       1 core.go:33] start module:tcp success !
I1019 08:30:46.060155       1 core.go:31] starting module:https
I1019 08:30:46.060167       1 core.go:33] start module:https success !
I1019 08:30:46.160517       1 core.go:31] starting module:ssh
I1019 08:30:46.064747       1 grpcserver.go:108] channelz server listening address is not configured
I1019 08:30:46.064784       1 grpcserver.go:99] log server listen on 0.0.0.0:51010
I1019 08:30:46.064867       1 grpcserver.go:132] metrics server listen on 0.0.0.0:6000
I1019 08:30:46.065105       1 tcp.go:55] the tcp server of the cloud tunnel listen on 0.0.0.0:6443
I1019 08:30:46.068209       1 grpcserver.go:68] the stream server of the cloud tunnel  listen on 0.0.0.0:9000
I1019 08:30:46.156762       1 httpsserver.go:59] the https server of the cloud tunnel listen on 0.0.0.0:10250
I1019 08:30:46.160960       1 httpsserver.go:59] the https server of the cloud tunnel listen on 0.0.0.0:9100
I1019 08:30:46.161182       1 core.go:33] start module:ssh success !
I1019 08:30:46.161242       1 core.go:31] starting module:httpProxy
I1019 08:30:46.161290       1 core.go:33] start module:httpProxy success !
I1019 08:31:07.895272       1 streaminterceptor.go:167] start verifying the token !
I1019 08:31:07.895379       1 streaminterceptor.go:187] token verification successful node = edge-qtjc
I1019 08:31:07.895553       1 streaminterceptor.go:210] node added successfully node = edge-qtjc
E1019 08:31:26.783172       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:46175->10.222.0.10:53: i/o timeout
E1019 08:31:27.285143       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:45134->10.222.0.10:53: i/o timeout
E1019 08:31:31.862515       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:37910->10.222.0.10:53: i/o timeout
E1019 08:31:36.365369       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:60301->10.222.0.10:53: i/o timeout
E1019 08:31:36.365400       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:40083->10.222.0.10:53: i/o timeout
E1019 08:31:36.460754       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:35861->10.222.0.10:53: i/o timeout
E1019 08:31:47.759313       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:37757->10.222.0.10:53: i/o timeout
E1019 08:31:47.759357       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:55156->10.222.0.10:53: i/o timeout
E1019 08:33:59.080673       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:42781->10.222.0.10:53: i/o timeout
E1019 08:34:50.573415       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:48726->10.222.0.10:53: i/o timeout
E1019 08:42:33.987313       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:35809->10.222.0.10:53: i/o timeout
E1019 08:43:02.663839       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:47544->10.222.0.10:53: i/o timeout
E1019 08:43:50.354488       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:53080->10.222.0.10:53: i/o timeout
E1019 08:44:29.856502       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:32938->10.222.0.10:53: i/o timeout
E1019 08:44:34.861664       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:54054->10.222.0.10:53: i/o timeout
E1019 08:46:17.362289       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:36495->10.222.0.10:53: i/o timeout
E1019 08:46:22.194027       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:37007->10.222.0.10:53: i/o timeout
E1019 08:47:10.962906       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:34400->10.222.0.10:53: i/o timeout
E1019 08:47:15.962614       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:45281->10.222.0.10:53: i/o timeout
E1019 08:47:37.826067       1 proxy.go:80] DNS parsing error: lookup master on 10.222.0.10:53: read udp 10.211.0.90:39045->10.222.0.10:53: i/o timeout

**Comment by qa137** [comment]
相应的coredns日志输出

**coredns日志日志输出**
ubuntu@VM-0-15-ubuntu:~$ sudo crictl logs f25f70e9874c0
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.8.4
linux/amd64, go1.16.4, 053c4d5
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:49463->183.60.83.19:53: i/o timeout
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:42044->183.60.82.98:53: i/o timeout
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:47407->183.60.82.98:53: i/o timeout
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:38502->183.60.82.98:53: i/o timeout
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:57553->183.60.82.98:53: i/o timeout
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:35373->183.60.83.19:53: i/o timeout
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:45316->183.60.82.98:53: i/o timeout
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:60913->183.60.83.19:53: i/o timeout
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:44393->183.60.82.98:53: i/o timeout
[ERROR] plugin/errors: 2 62807288941283895.7453585973550849141. HINFO: read udp 10.211.0.10:47820->183.60.82.98:53: i/o timeout

**Comment by dodiadodia** [comment]
@qa137 这个是 ubuntu 节点初始化的时候内核模块配置的问题，可以这么处理：
修改这个文件 /etc/modules-load.d/modules.conf，填下下面的内容： 
br_netfilter
iptable_nat
ip_vs
ip_vs_sh
ip_vs_rr
ip_vs_wrr

主要原因是 ubuntu 重启后br_netfilter这个内核模块没有 modprobe，导致pod 之间互访会有问题
