### ISSUE TITLE
集群内新增一个边缘节点后，该节点上的edge-coredns无法正常启动

### ISSUE THREAD

**Issue by whk06** [superedge/superedge#432]
各位好，目前有个疑问想请教一番：
我在集群内额外新增了一个节点(tc)(之前已有pre001这个边缘节点)，该新增的节点上的edge-coredns组件总是无法正常启动，查看日志提示 `Listen: listen tcp 169.254.20.11:53: bind: cannot assign requested address` ，经检查发现该节点ping 169.254.20.11 不通，而之前已经加入集群的节点是可以ping通的，想请问一下针对一个集群内有多边缘节点的这种情况，该如何处理呢？还望大佬们可指点迷津，不吝感谢！
![列表](https://user-images.githubusercontent.com/66070416/195355562-1bfd20da-e100-4b48-967e-a80533d5320c.jpg)
![日志](https://user-images.githubusercontent.com/66070416/195355644-1ec6b288-ff24-4c92-9bb5-0b7c06bac2cc.jpg)

**Comment by dodiadodia** [comment]
@whk06 你看下你的这个有问题的节点上，有没有下面这个虚拟网卡，ip 就是 169.254.20.11
<img width="842" alt="image" src="https://user-images.githubusercontent.com/4024470/195485891-d1469ce8-72d3-47d3-9351-7a7a938fa45f.png">

**Comment by whk06** [comment]
@dodiadodia 我用 `ip addr` 查了一下，确实没有对应 ip 为 `169.254.20.11` 的网卡，请问该如何添加呢？
![网卡](https://user-images.githubusercontent.com/66070416/195493037-a1c0e2c2-36c8-4adb-b7fe-a778151cd743.png)

**Comment by dodiadodia** [comment]
帮忙截个图看下下面这个服务的配置是否正确：

**Comment by whk06** [comment]
目前截图如下，其中lite-apiserver.service的配置不存在。
![lite-apiserver](https://user-images.githubusercontent.com/66070416/195495675-372b8522-2796-4978-9ebc-e079ba2118b1.png)

**Comment by dodiadodia** [comment]
@whk06 这里用这个地址cat 一下
<img width="543" alt="image" src="https://user-images.githubusercontent.com/4024470/195496777-5f44963b-4baf-4eea-ad5b-520624229ccb.png">

**Comment by whk06** [comment]
@dodiadodia cat后的内容如下：

root@edge-node-tc:~# cat /etc/systemd/system/lite-apiserver.service 

[Unit]
Description=lite-apiserver

[Service]
Environment=QCLOUD_NORM_URL=
ExecStart=/usr/bin/lite-apiserver --ca-file=/etc/kubernetes/pki/lite-apiserver-ca.crt --tls-cert-file=/etc/kubernetes/edge/lite-apiserver.crt --tls-private-key-file=/etc/kubernetes/edge/lite-apiserver.key --kube-apiserver-url=kubernetes.default --kube-apiserver-port=6443 --port=51003 --tls-config-file=/etc/kubernetes/edge/tls.json --file-cache-path=/data/lite-apiserver/cache --sync-duration=120 --timeout=3 --v=4
Restart=always
RestartSec=10
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target

**Comment by whk06** [comment]
@dodiadodia 我在lite-apiserver.service的配置中增加了 `ExecStartPre=-/bin/bash -c "ip link add tkeedgedns type dummy; ip addr add 169.254.20.11 dev tkeedgedns"`，现在新增了 `169.254.20.11` 这一网卡。然而目前提示访问 `Kubernetes.default` 超时。
![timeout](https://user-images.githubusercontent.com/66070416/195516448-b230c657-27e3-4600-81e9-52bb24b46c98.png)

**Comment by dodiadodia** [comment]
@whk06 如果 lite-apiserver 这个 systemd 文件都有问题的话，这个节点配置一定有问题（不知道你这个部署的版本号）；建议下载新版后重新接入一下这个节点

**Comment by whk06** [comment]
@dodiadodia 使用的包是 `edged-linux-amd64-v0.7.0-k8s-1.20.6.tgz` ，采用离线安装方式，操作系统为 `ubuntu18.04`，是在vmware workstation中安装的虚拟机。之前已经重装多次，每次重装前都有执行 `reset` 命令，然而每次的问题都一样。

现在看这个节点上，是没有Flannel和cni0网卡的缘故，请问大佬有解决方案吗？

**Comment by dodiadodia** [comment]
@whk06 那我大概了解了，应该是在 0.7.0 版本的某个时候的 bug，发布的 lite-apiserver 的版本缺少了虚拟网卡的配置；后来这个 bug 修复了，建议用 0.8.0 版本重新搞一下；当时状态的 bug 要手动修复的话可能比较麻烦了

**Comment by whk06** [comment]
@dodiadodia 请问一下，0.7.0 版本目前已在生产环境使用，是否有升级到 0.8.0 的流程呢？目前不太敢直接升级操作。

**Comment by dodiadodia** [comment]
@whk06 可以试一下：直接下载用 0.8.0 的 edgeadm版本，在 worker 节点上 做 join 操作...测试下

**Comment by whk06** [comment]
@dodiadodia 好的我会去测试一下。目前还想请问，若是整个集群都想从 0.7.0 升级到 0.8.0 ，是不是只能将集群进行重装呢？

**Comment by liguobao** [comment]
我这边正常安装完之后，无法联网了。
感觉是云服务器的网卡没了。
```
cni0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.233.0.1  netmask 255.255.255.0  broadcast 10.233.0.255
        inet6 fe80::2079:3aff:fe93:e7d1  prefixlen 64  scopeid 0x20<link>
        ether 22:79:3a:93:e7:d1  txqueuelen 1000  (Ethernet)
        RX packets 1634  bytes 134716 (134.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1633  bytes 2195045 (2.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.8  netmask 255.255.240.0  broadcast 172.17.15.255
        inet6 fe80::5054:ff:feba:4c64  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:ba:4c:64  txqueuelen 1000  (Ethernet)
        RX packets 3855  bytes 3990313 (3.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1757  bytes 223610 (223.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.233.0.0  netmask 255.255.255.255  broadcast 10.233.0.0
        inet6 fe80::6c43:f9ff:fee5:c6e5  prefixlen 64  scopeid 0x20<link>
        ether 6e:43:f9:e5:c6:e5  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 12 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 49407  bytes 23765331 (23.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 49407  bytes 23765331 (23.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```
