### ISSUE TITLE
[Question] Prometheus采集不到边端mysql exporter数据

### ISSUE THREAD

**Issue by geniuslc11** [superedge/superedge#444]
Prometheus可以采集到边端node exporter数据，但是采集不到边端mysql exporter数据，具体报错如下：

mysql exporter:
![image](https://user-images.githubusercontent.com/40260032/203880666-e247b0a5-e29e-4b9c-9812-ae4d5d3fba94.png)

prometheus configmap
![image](https://user-images.githubusercontent.com/40260032/203880712-0ffe77e2-e7e2-4f5b-b97e-3717f497bdb8.png)

superedge版本：
![image](https://user-images.githubusercontent.com/40260032/203687615-df9ef49c-bd30-459e-95e5-f9a9be58c6c9.png)

K8S版本：1.20.6

mysql pod网络      
hostNetwork: true

**Comment by liguobao** [comment]
目测是所有的监控信息都无法上报

**Comment by dodiadodia** [comment]
@liguobao 更新的新版 tunnel 已经可以解决此问题，关闭
