### ISSUE TITLE
搭建高可用集群 除init的master节点外其余master节点缺少文件

### ISSUE THREAD

**Issue by tianxin8206** [superedge/superedge#446]
**What happened**:
搭建三个master节点，除了init的master节点外，剩余两个join的master节点缺少egress-selector-configuration.yaml、kube-scheduler-config.yaml和kube-scheduler-policy.cfg、tunnel-anp-client证书文件，导致kube-scheduler-master和kube-apiserver-master无法正常启动。
**What you expected to happen**:
修复该问题。
**How to reproduce it (as minimally and precisely as possible)**:
搭建多master集群。

**Environment**:
- SuperEdge version: 0.8
- Kubernetes version (use `kubectl version`): 1.22.6
- OS (e.g. `cat /etc/os-release`): centos7.9
- Kernel (e.g. `uname -a`): 5.4
- Hardware configuration (e.g. `lscpu`) 4

**Comment by dodiadodia** [comment]
@tianxin8206 这个问题已经在v0.8.2版本解决，可以试用测试下
