### ISSUE TITLE
启动pods时，显示proxy error 的错误

### ISSUE THREAD

**Issue by feisc** [superedge/superedge#448]
在superEdge0.8.1，k8s:1.22的版本上部署deployment 时，出现了proxy error的错误。
![image](https://user-images.githubusercontent.com/22266880/207253614-5b07ec6e-fda3-4679-8b11-b78bcf1ac880.png)
而在lg-edgedev-38的服务器上，10250 的端口是开的
![image](https://user-images.githubusercontent.com/22266880/207253782-590ac350-638d-48cb-8e2d-cfd7289cb1cc.png)
同样的yaml 在superEdge0.7.0 上部署deployment 是正常的，请问大佬们这个要怎么解决？
@dodiadodia，@malc0lm ，@00pf00

**Comment by dodiadodia** [comment]
@feisc 不知道您 log 的这个 pod 是在云上节点还是边缘节点？之前的 tunnel 版本有一些设计缺陷，能够支持边缘 edge 节点的 pod 进行 log/exec，但是无法同时支持云上 worker 节点和 边缘 edge 节点。新的v0.8.2版本已经解决的这个缺陷，可以试用一下新的版本：
https://github.com/superedge/edgeadm/releases/tag/v0.8.2
