### ISSUE TITLE
Reduce the time for multiple tunnel cloud pods to update the node name and ip mapping to configmap

### ISSUE THREAD

**Issue by 00pf00** [superedge/superedge#65]
**What would you like to be added/modified**:
When the tunnel cloud pod updates the configmap, only the node name information related to the pod is updated when the configmap is updated
**Why is this needed**:
In the case that there are multiple copies of the deployment of tunnel cloud, when multiple edge nodes connect to the cloud, it will cause conflicts in the configmap of the tunnel cloud update cordons hosts plug-in.The tunnel attempts to re-update the configmap cycle is one minute, which will cause the node information connected to the cloud to take a long time to update to the configmap.

**Comment by neweyes** [comment]
It will be nice to discuss the details with you
