### ISSUE TITLE
这个有无成功案例？

### ISSUE THREAD

**Issue by fengnex** [superedge/superedge#79]
或者，建议提供一些示例应用
这样有助于展示这个项目的核心价值

**Comment by neweyes** [comment]
At present, supredge has been used in many business scenarios, but most of them are business cases, so it is not suitable to publish the specific installation and deployment information to this project. We are also planning to sort out the open source cases

**Comment by fengnex** [comment]
Look forward to being able to see relevant typical cases you mentioned that can express the value of superedge soon
