### ISSUE TITLE
[Question] Node communication in edge senarios

### ISSUE THREAD

**Issue by joker-joker-joker** [superedge/superedge#88]
CNI plugins such as flannel require that the network between nodes are reachable, but in edge scenarios, it often appears that edge nodes and cloud nodes belong to different local area networks, and the cloud nodes  are generally assigned public network IP while edge nodes will not. In this scenario, how should we solve the communication problem between edge nodes and cloud nodes? Is it by extending the CNI to the edge node, or is it through traffic interception at the application layer or the transport layer? Does superedge consider this scenario?
Thanks

**Comment by neweyes** [comment]
This is a very good question. If you do not want services to be accessed across regions, you can use the [serviceGroup](https://github.com/superedge/superedge/blob/main/docs/components/serviceGroup.md) capability provided by SuperEdge. if not, sd-wan network solution is recommended
