### ISSUE TITLE
[Question] Support for k3s cluster

### ISSUE THREAD

**Issue by aisensiy** [superedge/superedge#89]
Read the doc about [Prerequests](https://github.com/superedge/superedge/blob/main/docs/installation/install_via_edgeadm.md#prerequisite) but still want to know if it is possible to support k3s cluster.

Or is there any plan to support?

**Comment by neweyes** [comment]
Currently we intend to concentrate on solving the challenges using Kubernetes in edge scenarios，using a cluster created by kubeadm is one of the best ways. If you complete the k3s compatibility, we will be very expected.
