### ISSUE TITLE
云端apiserver不能访问边端的webhook server

### ISSUE THREAD

**Issue by moshushi1999** [superedge/superedge#94]
在边缘集群上部署了nginx ingress controller，希望能通过ingress方式来访问应用
在为应用创建ingress时报错
![image](https://user-images.githubusercontent.com/42575760/115837367-15317f80-a44b-11eb-8010-59cefbe33546.png)

后定位原因是云端的apiserver无法访问边端的webhook server导致

**Comment by neweyes** [comment]
In the edge scenario, the cloud nodes often can't access the edge nodes directly. If the webhook server runs on the edge nodes, there will be a phenomenon that the apiserver can't access the webhook server. There are two solutions:
1. Use node affinity or other ways to let webhook server run on cloud nodes. This method is relatively simple, but can not meet all the needs
2. Through a special channel, the apserver in the cloud can access the webhook server running on the edge nodes through this channel. This method is complicated and needs to be designed carefully.

**Comment by neweyes** [comment]
@00pf00

**Comment by WaylandWong** [comment]
I think you can set `admissionWebhooks.enabled` to false while using helm to install nginx-ingress controller, or just remove admissionWebhooks related resources.

---

建议可以把nginx-ingress 的webhook关掉，或者删掉webhook相关的资源就可以了。

**Comment by moshushi1999** [comment]
您好！您发给我的信件已经收到。

**Comment by moshushi1999** [comment]
您好！您发给我的信件已经收到。
